# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=200)),
                ('text', models.CharField(default=0, max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='Static/images/works/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наши работы',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=200)),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Типы работ',
            },
        ),
    ]
