# Generated by Django 2.0.7 on 2018-08-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170315_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(null=True, upload_to='app/static/images/news/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости и статьи',
            },
        ),
        migrations.CreateModel(
            name='NewsPhotoSpecif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News/', verbose_name='Фото')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_photos', to='app.News', verbose_name='Фото в галлерею')),
            ],
            options={
                'verbose_name': 'Фото в галлерею',
                'verbose_name_plural': 'Фото в галлерею',
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='workType',
        ),
        migrations.RemoveField(
            model_name='workphoto',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='WorkPhoto',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
