# Generated by Django 2.0.7 on 2018-08-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='short_description',
        ),
    ]
