# Generated by Django 2.0.7 on 2018-12-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181216_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsphotospecif',
            name='caption',
            field=models.TextField(default='', verbose_name='Подпись'),
        ),
    ]
