# Generated by Django 2.0.7 on 2018-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_newsphotospecif_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphotospecif',
            name='caption',
            field=models.CharField(default='', max_length=255, verbose_name='Подпись'),
        ),
    ]
